name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", ]
        rust-target: ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]

    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 安装 Rust 工具链并设置目标架构
      - name: Install Rust for ${{ matrix.rust-target }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.rust-target }}

      # 安装 uv
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      # 使用 uv 和 maturin 构建项目，指定目标架构
      - name: Build with maturin for ${{ matrix.rust-target }}
        run: |
          export RUST_TARGET=${{ matrix.rust-target }}
          uv venv
          uv pip install maturin
          uv run maturin build --target ${{ matrix.rust-target }}

      # 可选：将构建产物上传为 artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel-${{ matrix.python-version }}-${{ matrix.rust-target }}
          path: dist/*.whl