name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", ]
        architecture: ["x86_64", "aarch64"]

    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 安装 Rust 工具链
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # 安装 uv
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      # 安装 cross-compilation tools for aarch64
      - name: Install cross-compilation tools
        if: matrix.architecture == 'aarch64'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      # 使用 uv 和 maturin 构建项目
      - name: Build with maturin
        run: uv build

      # 可选：将构建产物上传为 artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel-${{ matrix.python-version }}
          path: dist/*.whl
