name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 安装 Rust 工具链
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # 安装 maturin
      - name: Install maturin
        run: pip install maturin

      # 构建 Rust 项目并生成 Python 轮子
      - name: Build with maturin
        run: maturin build --release --out dist

      # 安装构建的轮子
      - name: Install the package
        run: pip install dist/computing_lib-*.whl

      # 可选：将构建产物上传为 artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel-${{ matrix.python-version }}
          path: dist/*.whl

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
